openapi: 3.0.0
info:
  title: Agency
  version: '1.0'
servers:
  - url: 'http://localhost:8080/api/v1/agency'
paths:
  '{agencyId}':
    parameters:
      - schema:
          type: string
        name: agencyId
        in: path
        required: true
        description: uuid of an existing agency.
    get:
      summary: Get Agency profile by agency id
      tags:
        - Agency profile
      responses:
        '200':
          description: Agency
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgencyProfile'
              examples:
                example with two commissions:
                  value:
                    brandName: Santufei
                    legalName: Santufei
                    commissions:
                      - routeType:
                          - INTERNATIONAL
                          - LOCAL
                          - CUSTOM
                        commissionType: AMOUNT
                        amount: 10
                      - routeType:
                          - INTERNATIONAL
                          - LOCAL
                          - CUSTOM
                        commissionType: PERCENT
                        amount: 5
        '403':
          description: It is not possible to get other user profile
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user
    post:
      tags:
        - Agency profile
      summary: Update agency profile
      responses:
        '204':
          description: Agency Updated
      description: Update the infromation of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgencyProfile'
              examples:
                example with two commissions:
                  value:
                    brandName: Santufei
                    legalName: Santufei
                    commissions:
                      - routeType:
                          - INTERNATIONAL
                          - LOCAL
                          - CUSTOM
                        commissionType: AMOUNT
                        amount: 10
                      - routeType:
                          - INTERNATIONAL
                          - LOCAL
                          - CUSTOM
                        commissionType: PERCENT
                        amount: 5
components:
  schemas:
    AgencyProfile:
      title: Profile
      type: object
      description: agency profile
      x-examples:
        sample profile:
          brandName: Sierra
          legalName: Fergusoon
          email: sierra@gmail.com
          phone: '+77078904592'
      properties:
        firstName:
          type: string
        legalName:
          type: string
        commissions:
          $ref: '#/components/schemas/Commissions'
    Commissions:
      title: commissions
      type: object
      description: Agency commissions
      properties:
        routeType:
          type: array
        commissionType:
          type: string
        amount:
          type: integer
