openapi: 3.0.0
info:
  title: fare-rules-and-ancillaries
  version: '1.0'
  contact: {}
  description: 'Manage Airline ancillaries'
servers:
  - url: 'http://localhost:3000'
tags: [{'name':''}]
paths:
  /v1/api/dictionaries/fare-options:
    get:
      summary: 'get paginated, filtered and sorted fare rules and ancillaries'
      description: 'Get Airline fare rules summary'
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  totalCount:
                    type:
                      - string
                      - number
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        name:
                          type: string
                        category:
                          type: string
                        type:
                          type: string
                        translations:
                          type: array
                          items:
                            $ref: ../models/Translation.v1.yaml
      operationId: get-fare-options
      parameters:
        - schema:
            type: number
          in: query
          name: page
          required: true
        - schema:
            type: number
          in: query
          name: size
          required: true
        - schema:
            type: string
          in: query
          name: name
        - schema:
            type: string
          in: query
          name: category
          description: Fare Rule or Ancillary
        - schema:
            type: string
          in: query
          name: type
  /v1/api/dictionaries/ancillaries:
    post:
      summary: Create Ancillary
      description: 'Create Airline ancillary'
      tags: []
      responses:
        '201':
          description: Created
      operationId: post-v1-api-dictionaries-ancillaries-id
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/AncillaryModel.v1.yaml
  /v1/api/dictionaries/fare-rules:
    post:
      summary: Add Fare Rule
      description: 'Cread Airline fare rule'
      tags: []
      responses:
        '201':
          description: Created
      operationId: post-v1-api-dictionaries-fare-rules
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/AddFareRuleRequestModel.v1.yaml
  /v1/api/dictionaries/fare-rules/{id}:
    put:
      summary: Update Fare Rule identified by a given ID
      description: 'Update Airline fare rule'
      tags: []
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties: {}
      operationId: put-v1-api-dictionaries-fare-rules
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/AddFareRuleRequestModel.v1.yaml
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
        description: ID of the Fare Rule
    delete:
      summary: 'Delete Fare Rule with a given ID '
      description: 'Delete Airline fare rule'
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: delete-v1-api-dictionaries-fare-rules-id
  '/v1/api/dictionaries/ancillaries/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Ancillary ID
    put:
      summary: Update Ancillary
      description: Update Airline ancillary
      tags: []
      responses:
        '204':
          description: No Content
      operationId: put-v1-api-dictionaries-ancillaries-id
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/AncillaryModel.v1.yaml
    delete:
      summary: Delete Ancillary
      description: Update Airline ancillary
      tags: []
      responses:
        '200':
          description: OK
      operationId: delete-v1-api-dictionaries-ancillaries-id
components:
  schemas: {}
