openapi: 3.0.0
info:
  title: Template.v1
  version: '1.0'
  description: Generic Tamplate API
servers:
  - url: 'http://localhost:3000'
paths:
  /api/v1/templates:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TemplateSummary'
      operationId: get-api-v1-templates
      description: Get paginated list of N last created templates
    post:
      summary: ''
      operationId: post-api-v1-templates
      responses:
        '200':
          description: OK
      description: Create Template
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTemplateRequest'
  '/api/v1/templates/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
      operationId: get-api-v1-templates-id
      description: Get template payload by template Id
components:
  schemas:
    CreateTemplateRequest:
      title: CreateTemplateRequest
      type: object
      properties:
        type:
          type: string
        name:
          type: string
        description:
          type: string
        data:
          type: object
          description: Template payload
      required:
        - type
        - name
        - data
      x-examples:
        Create RBD Matrix Template:
          type: RBD Matrix
          name: Saved matrix - 1
          data:
            cabinClass: ECONOMY
            totalSearCount: 80
            fareClasses:
              - fareClassDesignator: 'Y'
                seatCount: 10
                timeLimit: 120
              - fareClassDesignator: 'Y'
                seatCount: 70
                timeLimit: 60
    TemplateSummary:
      title: TemplateSummary
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
