openapi: 3.0.0
info:
  title: booking
  version: '1.0'
  description: Booking management 
  contact:
    name: Asset Yelemessov
    url: farel.dev
    email: asset@farel.io
servers:
  - url: 'http://localhost:8080/api/v1'
tags:
  - name: Search flights
    description: Paginated list of Bookings
  - name: Create booking
paths:
  /public/flights:
    get:
      operationId: search-flights
      description: search flights by given search criteria
      tags:
        - Search flights
      parameters:
        - name: origin
          in: query
          required: true
          schema:
            type: string
          description: Origin Airport Code
          example: NQZ
        - name: destination
          in: query
          required: true
          schema:
            type: string
          description: Destination Airport Code
          example: ALA
        - name: flightDate
          in: query
          required: true
          schema:
            type: string
            format: date
          example: 2020-01-01
          description: Flight date in the format defined by ISO
        - name: tripType
          in: query
          required: true
          schema:
            type: string
            enum: ["OW", "RT"]
          description: One-Way vs. Round-Trip indicator
          example: OW
        - name: airlines
          in: query
          required: true
          schema:
            type: array
            items: 
              type: string
            minItems: 1
          description: Airline IDs
        - name: segmentGroupId
          in: query
          schema:
            type: string
          description: Departing Flight ID for Round-Trip
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: pageSize
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 20
      responses:
        "200":
          description:
            List of flights 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlightsResponse'
  /public/bookings:
      post:
        operationId: create-booking
        description: Create booking
        tags:
          - Create booking
        requestBody:
          $ref: '#/components/requestBodies/BookingRequestBody'
        responses:
          "204":
            description: Booking was created successfully
components:
  requestBodies:
    BookingRequestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              flights:
                type: array
                items:
                  properties:
                    flightNumber:
                      type: string
                    flightDate:
                      type: string
                      format: datetime
              passengers:
                type: array
                items:
                  properties:
                    passengerType:
                      type: string
                      example: ADT
                    firstname:
                      type: string
                    lastname:
                      type: string
                    gender:
                      type: string
                    birthday: 
                      type: string
                      format: date
                    citizenship:
                      type: string
                      example: KZ
                    documentId:
                      type: string
                    documentExpireDate:
                      type: string
                      format: datetime
              contactPerson:
                type: object
                properties:
                  firstname:
                    type: string
                  lastname:
                    type: string
                  email:
                    type: string
                  phone:
                    type: string
  schemas:
    FlightsResponse:
      type: object
      properties:
        totalCount:
          type: integer
        data:
          type: array
          items: 
            $ref: '#/components/schemas/Flight'
    Flight:
      type: object
      properties:
        origin:
          type: string
          example: "ALA"
        destination:
          type: string
          example: "SVO"
        departTime:
          type: string
          pattern: "HH:MM"
        arriveTime:
          type: string
          pattern: "HH:MM"
        arriveDateOffset:
          type: string
          example: "-1"
        duration:
          type: integer
          description: Flight duration in minutes
          example: 120
        stops:
          type: array
          items:
            properties:
              airport:
                type: string
                example: NQZ
              stopDuration:
                type: integer
                description: "Stop duration in minutes"
                example: 60
        flightSegments:
          type: array
          items:
            properties:
              flightNumber:
                type: string
              aircraft:
                type: string
              flightDuration:
                type: integer
              stopDuration:
                type: integer
              origin:
                type: object
                properties:
                  city: 
                    type: string
                  airportName:
                    type: string
                  airportCode:
                    type: string
                  date:
                    type: string
                    format: datetime
                  time: 
                    type: string
                    pattern: "HH:MM"
              destination:
                type: object
                properties:
                  city: 
                    type: string
                  airportName:
                    type: string
                  airportCode:
                    type: string
                  date:
                    type: string
                    format: date
                  time: 
                    type: string
                    pattern: "HH:MM"
        totalPrice:
          type: string
          example: "$500"
